stages:
  start:
    text: 'Wenn du nicht auch noch beinahe gefressen werden willst, hörst du mir besser zu.'
    answers:
      flow:
        - ':"Worauf willst du hinaus?"'
        - '!stage quest'
        - ':"Na gut, was willst du?"'
        - '!stage quest'
        - ':"Ich komme schon klar, such dir wen anders."'
        - '!end'

  from-reparaturarbeiten:
    text: 'In der Zwischenzeit könntest du noch im Camp aushelfen, frag doch die anderen mal - oder z.B. noch einige der wildgewordenen Wölfe plattmachen.\nWas meinst du?'
    answers:
      flow:
        - ':"Ach nein, Schimmerwölfe jagen ist nicht so meins, die sind doch schön anzusehen."'
        - '!stage quest'
        - ':"Schimmerwölfe? Ich tu es für dich, aber warum, sie sind doch schön anzusehen."'
        - '!stage quest'

  quest:
    actions:
      flow:
        - '!text "Hörzu: Ich habe kein Problem mit Tieren, aber wenn sie eins mit mir haben, ist das sehr wohl ein Problem! Normalerweise halten sich fast alle Viecher von uns fern. Aber hier gibt es Wölfe, die nicht zögern jeden anzugreifen, der ihnen zu nahe kommt. Wer weiß, ob da nicht Magie im Spiel ist."'
        - '~8s'
        - '!text.player "Und ich soll die Wölfe jetzt töten, natürlich. Wo finde ich sie?"'
        - '~4s'
        - '!stage quest-accept'
  
  quest-accept:
    text: 'Ein Stück südwestlich von hier im Wald ist ein alter Schrein an einer eingestürzten Brücke. Dort in der Nähe haben sie mich schon einmal angegriffen. Schau am besten dort.'
    answers:
      flow:
        - ':"Na schön, ich werde mich um diese Biester kümmern."'
        - '!quest.start this.woelfe'
        - '!text "Du würdest dem Lager damit sehr helfen! Komm wieder zu mir, wenn du sie erledigt hast."'
        - ':"Ich habe es mir anders überlegt, die armen Tiere können ja auch nichts dafür."'
        - '!text "Fressen und gefressen werden..."'