name: Petze oder nicht Petze
desc: Sprich mit Wache Mark
locked: false
author: Heracklos/Kiachan
ordered: true
hidden: true
required: 0
trigger:
  '0':
    type: quest.completed
    args:
      quest: world.wyzima.start-einsamer-schurke
    actions:
      '0':
        type: quest.start
        args:
          quest: world.wyzima.petz.start-petze
      '1':
        type: rcconversations.conversation.start
        args:
          host: this.wache
          conv: this.start
objectives:
  '0':
    name: Verrate Lars bei der Wache Mark
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: this.start
          stage: way1
        actions:
          '0':
            type: player.give.money
            args:
              amount: 20s
          '1':
            type: rcskills.hero.addxp
            args:
              exp: 100
          '2':
            type: rcconversations.host.save
            args:
              host: this.wache
              conv: this.end-quest
          '3':
            type: quest.complete
            args:
              quest: this.start-petze
  '1':
    name: Nimm Lars bei der Wache Mark in Schutz
    hidden: true
    optional: true 
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: this.start
          stage: way2
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: this.wache
              conv: this.end-quest      
          '1':
            type: teleport.location
            args: 
              world: world
              x: 63
              y: 58
              z: 205
          '2':
            type: quest.start
            args:
              quest: world.wyzima.flucht.start-quest
          '3':
            type: quest.complete
            args:
              quest: this.start-petze
  '2':
    name: Streite alles ab
    hidden: true
    optional: true 
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: this.start
          stage: way3
        actions:
          '0':
            type: rcskills.hero.addxp
            args:
              exp: 150
          '1':
            type: rcconversations.host.save
            args:
              host: this.wache
              conv: this.end-quest               
          '2':
            type: quest.complete
            args:
              quest: this.start-petze
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 200
  '1':
    type: player.give.money
    args:
      amount: 5s
  '2':
    type: rcconversations.host.save
    args:
      host: world.wyzima.petz.wache
      conv: world.wyzima.petz.end-quest