stages:
  start:
    text: Hey du warte mal! Du siehst mir verdächtig aus!
    answers:
      '1':
        text: Verdächtig? Wieso?
        actions:
          A:
            type: STAGE
            args:
              stage: stage2
      '2':
        text: Ah ich geh dann mal...
        actions:
          A:
            type: END
  stage2:
    text: Ich habe gehört du wurdest mit einem Schurken namens Lars|gesehen... Stimmt das?
    answers:
      '1':
        text: Ja er versteckt sich unten im 'Messers Schneide', gibt es ein Kopfgeld?
        actions:
          A:
            type: STAGE
            args:
              stage: stage3
      '2':
        text: Nein das muss ein Irrtum sein tut mir leid.
        actions:
          A:
            type: STAGE
            args:
              stage: stage4
  stage3:
    text: Ja es gibt tatsächlich ein Kopfgeld aber sagmal|woher kennst du ihn?
    answers:
      '1':
        text: Ah nur flüchtig vom sehen, ich war dort um was zu trinken.
        actions:
          A:
            type:  STAGE
            args:
              stage: way1
      '2':
        text: Ich hab ihm geholfen seine Klamotten wieder zu bekommen! Der ärmste war total am frieren.
        actions:
          A:
            type: STAGE
            args:
              stage: way2
  way1:
    text: Nun gut ich will es dabei belassen. Hier nimm das Kopfgeld,|aber halte dich von solchen Typen fern.
    actions:
      A:
        type: END
  way2:
    text: Das dachte ich mir, du steckst mit ihm unter einer Decke!|Ab ins Gefängniss mit dir!
    actions:
      A:
        type: END
  stage4: 
    text: Bist du dir sicher? Es ist nicht umsonst ein Kopfgeld auf ihn|ausgesetzt, nette 20 Silber.
    answers:
      '1':
        text: Hm jetzt wo ich darüber nachdenke,er versteckt sich unten im 'Messers Schneide'.
        actions:
          A:
            type: STAGE
            args:
              stage: way1
      '2':
        text: Nein tut mir leid ich weiß wirklich nicht wer das sein soll.
        actions:
          A:
            type: STAGE
            args:
              stage: way3
  way3:
    text: Wie du meinst, aber ich werde ein Auge auf dich haben!
    actions:
      A:
        type: END