name: Der einsame Schurke
desc: Finde Lars Sachen 
locked: false
author: Heracklos/Kiachan
ordered: false
hidden: true
required: 0
trigger:
  '0':
    type: host.interact
    args:
      host: this.lars
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: this.lars
          conv: this.start-quest
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: this.start-quest
      stage: accept
    actions:
      '0':
        type: quest.start
        args:
          quest: this.start-einsamer-schurke
      '1':
        type: rcconversations.host.save
        args:
          host: this.lars
          conv: this.lars-1
objectives:
  '0':
    name: Finde alle versteckten Gegenstände
    trigger:
      '0':
        type: player.move # besser mal auf objective.completed umbauen, wenn das wieder geht!
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: this.lars
              conv: this.complete-quest
        requirements:  
          '0':
            type: player.has-item
            args:
              item: Rc90911
              amount: 1
          '1':
            type: player.has-item
            args:
              item: Rc90912
              amount: 1
          '2':
            type: player.has-item
            args:
              item: Rc90913
              amount: 1
          '3':
            type: player.has-item
            args:
              item: Rc90914
              amount: 1
          '4':
            type: player.has-item
            args:
              item: Rc90915
              amount: 1
  '1':
    name: Finde die Schurkenhose
    trigger:
      '0':
        type: player.interact
        args:
          world: world
          x: 36
          y: 31
          z: 138
        actions:
          '0':
            type: quest.item.add
            args:
              item: Rc90911
              amount: 1
  '2':
    name: Finde die Schurkenstiefel
    trigger:
      '0':
        type: player.interact
        args:
          world: world
          x: 57
          y: 40
          z: 163
        actions:
          '0':
            type: quest.item.add
            args:
              item: Rc90912
              amount: 1
  '3':
    name: Finde die Schurkenbrust
    trigger:
      '0':
        type: player.interact
        args:
          world: world
          x: 51
          y: 38
          z: 166
        actions:
          '0':
            type: quest.item.add
            args:
              item: Rc90913
              amount: 1
  '4':
    name: Finde den Schurkenkopfschutz
    trigger:
      '0':
        type: player.interact
        args:
          world: world
          x: 41
          y: 44
          z: 164
        actions:
          '0':
            type: quest.item.add
            args:
              item: Rc90914
              amount: 1
  '5':
    name: Finde den Dolch
    trigger:
      '0':
        type: player.interact
        args:
          world: world
          x: 48
          y: 35
          z: 153
        actions:
          '0':
            type: quest.item.add
            args:
              item: Rc90915
              amount: 1
  '6':
    name: Bringe Lars seine Sachen zurück
    hidden: true
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: this.complete-quest
          stage: finished
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 300
  '1':
    type: player.give.money
    args:
      amount: 5s20k
  '2':
    type: rcconversations.host.save
    args:
      host: this.lars
      conv: this.end-quest
  '3':
    type: quest.item.remove
    args:
      item: Rc90911
  '4':
    type: quest.item.remove
    args:
      item: Rc90912
  '5':
    type: quest.item.remove
    args:
      item: Rc90913
  '6':
    type: quest.item.remove
    args:
      item: Rc90914
  '7':
    type: quest.item.remove
    args:
      item: Rc90915