stages:
  start:
    actions:
      flow:
        - '!text "Willkommen in der Krone des Tianbaumes."'
        - ~2s
        - '!text.player "Was bedeutet das alles? Roshik sagte, Ihr würdet mir weiterhelfen?"'
        - ~2s
        - '!text "Übe dich in Geduld, junger Kaishi. Ich bin Lious, du kennst mich und du solltest mir nun gut zuhören."'
        - ~2s
        - '!text.player "Ich glaube wir haben aber keine Zeit für langanhaltende Geduld."'
        - ~2s
        - '!text "Wir haben alle Zeit die wir benötigen, um dich auf die kommenden, schweren Tage und Wochen vorzubereiten."'
        - ~1s
        - '!quest.complete this.aufstieg-zum-tianbaum'
#        - ~2s
#        - '!text.player "Denn du wirst die Wahl zwischen fünf Pfaden des Kampfes haben. Jeder Pfad bestimmt eine Klasse. Eine Lebensweise!"'
#        - ~2s
#        - '!text "Du wirst die Wahl haben zwischen dem Weg des Kriegers, Assassinen, Elementaristen, Klerikers oder dem des Waldläufers. Jeder Pfad ist einzigartig, wählt also weise."'
#        - ~2s
#        - '!text.player "Was muss ich tun? Wie wähle ich meinen Pfad?"'
#        - ~2s
#        - '!text "Gehe hinüber zu einem der fünf Ritualsteine, diese werden dir die einzelnen Pfade weiter erläutern, sobald du alle fünf Steine berührt hast, komme zu mir zurück."'
#        - ~1s
#        - '!quest.complete this.aufstieg-zum-tianbaum'