name: Frischer Fisch
desc: Hilf Andy beim Fischen
locked: false
author: Kiachan
ordered: false
required: 0
trigger:
  '0':
    type: host.interact
    args:
      host: world.bravaria.kia.frischer_fisch.andy
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.bravaria.kia.frischer_fisch.andy
          conv: world.bravaria.kia.frischer_fisch.start-quest
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: world.bravaria.kia.frischer_fisch.start-quest
      stage: accept
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.frischer_fisch.start
      '1':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.frischer_fisch.andy
          conv: world.bravaria.kia.frischer_fisch.complete-quest
objectives:
  '0':
    name: Angle ein Dutzend Fische für Andy
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.frischer_fisch.complete-quest
          stage: finished
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 150
  '1':
    type: player.give.item
    args:
      item: COOKED_FISH
      amount: 6
  '2':
    type: rcconversations.host.save
    args:
      host: world.bravaria.kia.frischer_fisch.andy
      conv: world.bravaria.kia.frischer_fisch.end-quest
  '3':
    type: player.remove.item
    args:
      item: RAW_FISH
      amount: 12
cooldown: 0
repeatable: false
