stages:
  start:
    actions:
      groups:
        swords: '?player.has-item(persistant:true) ../2-der-schmied/rostiges-schwert,10'
      flow:
        - '?swords'
        - '!stage end-both'
        - '?swords(negate:true)'
        - '!stage open-eisen'
  end-both:
    text: "Aus der Tatsache, dass du noch lebst, und aus der, dass du die Schwerter hast, nehme ich an, dass die Skelette Tot sind?"
    answers:
      flow:
        - ':"Ja, sie sind tot… oder was auch immer."'
        - '!text "Vielen Dank, dass du dich darum gekümmert hast."'
        - '~1s'
        - '!text.player "Musste ich ja wohl..."'
  open-eisen:
    text: "Und sind die Skelette tot?"
    answers:
      flow:
        - ':"Ja, sie sind tot… oder was auch immer."'
        - '!text "Vielen Dank dafür, aber vielleicht solltest du noch die restlichen Schwerter für Sakros sammeln."'
        - '~2s'
        - '!text.player "Jaja, schon gut..."'