stages:
  start:
    actions:
      groups:
        swords: '?player.has-item(persistant:true) ../2-der-schmied/schwert,10'
        end-both:
          - '!text "Vielen Dank, dass du dich darum gekümmert hast.", this.genam'
          - '~1s'
          - '!text.player "Musste ich ja wohl..."'
          - '!end'
        open-eisen:
          - '!text "Vielen Dank dafür, aber vielleicht solltest du noch die restlichen Schwerter für Sakros sammeln.", this.genam'
          - '~2s'
          - '!text.player "Jaja, schon gut..."'
          - '!end'
      flow:
        - '?swords'
        - '!text "Aus der Tatsache, dass du noch lebst, und aus der, dass du die Schwerter hast, nehme ich an, dass die Skelette Tot sind?", this.genam'
        - '?swords(negate:true)'
        - '!text "Und sind die Skelette tot?", this.genam'
        - '~3s'
        - '!text.player "Ja, sie sind tot… oder was auch immer."'
        - '!quest.complete this.skelette-in-der-hoehle'
        - '~2s'
        - '?swords'
        - '!end-both'
        - '?swords(negate:true)'
        - '!open-eisen'