name: Bauherr
desc: Fliege zu den Slums
locked: false
author: Kiachan
ordered: true
hidden: true
required: 0
worlds:
- world
trigger:
  '0':
    type: quest.completed
    delay: 5
    args:
      quest: world.bravaria.kia.tutorial.7-rueste-dich.start-rueste-dich
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.tutorial.8-bauherr.start-bauherr
objectives:
  '0':
    name: Fliege zu den neuen Slums und folge dem Kompass zu freien Grundstücken
    optional: true
    trigger:
      '0':
        type: player.move
        args:
          world: world
          x: 330
          y: 64
          z: -172
          radius: 3
  '1':
    name: Kaufe dein erstes Grundstück in den Slums
    hidden: true
    trigger:
      '0':
        type: rcregions.region.claim
        args:
          district: slums
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 270
  '1':
    type: player.give.compass
    args:
      world: world
      x: -1728
      y: 71
      z: -52
      name: Andy
  '2':
    type: rcconversations.host.save
    args:
      host: world.bravaria.kia.tutorial.7-rueste-dich.ruestmeister
      conv: world.bravaria.kia.tutorial.7-rueste-dich.1-ruestmeister
  '3':
    type: player.remove.compass
    args:
      name: Die neuen Slums
cooldown: 0
repeatable: false
