name: Osteromelett
desc: Bring dem Koch die Zutaten für das Omelett
locked: true
author: Kiachan
ordered: true
hidden: true
required: 0
trigger:
  '0':
    type: host.interact
    args:
      host: world.ostern.oster_omelett.koch
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.ostern.oster_omelett.koch
          conv: world.ostern.oster_omelett.start-quest
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: world.ostern.oster_omelett.start-quest
      stage: accept
    actions:
      '0':
        type: quest.start
        args:
          quest: world.ostern.oster_omelett.start-oster_omelett
      '1':
        type: rcconversations.host.save
        args:
          host: world.ostern.oster_omelett.koch
          conv: world.ostern.oster_omelett.koch-1
objectives:
  '0':
    name: Sammele 24 schmutzige Hühnereier
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          id: 90928
          types: TRASH
    requirements:
      '0':
        type: player.has-item
        args:
          item: Rc90928
          amount: 23
  '1':
    name: Sammle 12 Karotten
    hidden: true
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          item: 391
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.ostern.oster_omelett.koch
              conv: world.ostern.oster_omelett.complete-quest
    requirements:
      '0':
        type: player.has-item
        args:
          item: 391
          amount: 11
  '2':
    name: Bringe die Zutaten dem Koch
    hidden: true
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.ostern.oster_omelett.complete-quest
          stage: finished
complete-actions:
  '0':
    type: player.remove.item
    args:
      item: rc90928
      amount: 24
  '1':
    type: player.remove.item
    args:
      item: 391
      amount: 12
  '6':
    type: rcskills.hero.addxp
    args:
      exp: 250
  '7':
    type: rcconversations.host.save
    args:
      host: world.ostern.oster_omelett.koch
      conv: world.ostern.oster_omelett.end-quest
  '8':
    type: quest.item.add
    args:
      item: 90970
      amount: 15
  '9':
    type: player.give.item
    args:
      item: 90971
      amount: 1
cooldown: 0
repeatable: false
