name: Start in ein Abenteuer
desc: Wähle eine Klasse und erlerne die Grundfertigkeiten
ordered: false
author: Raid-Craft Team
required: 0
worlds:
- world
locked: false
trigger:
  '0':
    type: host.interact
    args:
      host: world.bravaria.kia.tutorial.1-neuer-rekrut.dean
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.bravaria.kia.tutorial.1-neuer-rekrut.dean
          conv: world.bravaria.kia.tutorial.1-neuer-rekrut.dean-start
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: world.bravaria.kia.tutorial.1-neuer-rekrut.dean-start
      stage: accept
    actions:
      '0':
        type: quest.start
        action-delay: 2
        args:
          quest: world.bravaria.kia.tutorial.1-neuer-rekrut.start-neuer-rekrut
      '2':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.tutorial.1-neuer-rekrut.dean
          conv: world.bravaria.kia.tutorial.1-neuer-rekrut.dean-end
objectives:
  '0':
    name: Rede mit Wulfgar und wähle eine Klasse
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-start
          stage: end
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 100
  '1':
    type: block.set
    args:
      x: -1732
      y: 68
      z: -55
      world: world
      block: air
  '2':
    type: block.set
    args:
      x: -1732
      y: 67
      z: -55
      world: world
      block: air
  '3':
    type: rcregions.restrict-to-region
    args:
      region: start_area
      message: Du bist noch nicht bereit den Startbereich zu verlassen
cooldown: 0
repeatable: false
