enabled: true
cooldown: 18h
global: false
execution-count: 4

actions:
  flow:
    - '!text.think "*Du siehst Mairi aufs Meer hinausblicken, ihre Haltung zeigt dir, dass sie Kummer hat*"'

requirements:
  flow:
    - '?quest.complete eisenkueste.hauptquest.1-was-ist-passiert'
    - '?quest.complete eisenkueste.hauptquest.2-reparaturarbeiten'

trigger:
  flow:
    - '@loc eisenkueste.npcs.mairi'