stages:
  start:
    text: "Hallo %player, was machst du hier bei den Feldern? Willst du wieder Erdäpfel klauen?"
    answers:
      flow:
        - ':"Ich klaue nicht, ich hole nur meinen Anteil. Du gehst wie immer deiner Arbeit nach?"'
        - '!text "Ja, und... ich bin wieder so nah an dem Brunnen."'
        - '~3s'
        - '!text.player "Was ist mit dem Brunnen? Immer noch Angst davor?"'
        - '~2s'
        - '!stage angst'
        - ':"Pssst, nicht so Laut, das darf keiner wissen."'
  angst:
    text: "Er ist gruselig, ich höre immer ein Grollen in seiner Nähe, hörst du es nicht?"
    answers:
      flow:
        - ':"Moment... irgendwas ist da, aber das ist sicher nur das Wasser, das da Geräusche macht."'
        - '!text "Danke, dass du versuchst mich zu beruhigen, aber ganz beruhigt bin ich noch immer nicht."'
        - '~4s'
        - '!text.player "Mach dir nicht so viele Gedanken."'
        - '~2s'
        - '!stage lutz'
        - ':"Moment... Nein ich höre nichts, du bildest dir das nur ein."'
        - '!text "Du glaubst mir also auch nicht."'
  lutz:
    text: "Hast du Lutz gesehen? Roschick hat ihm gesagt, er solle mir heute helfen. Wenn du ihn siehst sag ihm, dass ich auf ihn warte."
    answers:
      flow:
        - '?tag ankanor.lutz'
        - '-:"Nein ich habe ihn nicht gesehen. Soll ich ihm sagen, dass du nach ihm suchst, wenn ich ihn sehe?"'
        - '!text "Das wäre sehr nett von dir. Danke."'
        - '!tag ankanor.lewis-bitte'
        - '+:"[Lügen] Ja ich habe ihn gesehen. Er ist krank und kann nicht helfen kommen. Er sagte, du musst alleine klarkommen."'
        - '!text "Oh nein, ich hoffe es geht ihm bald besser."'
        - '+:"[Verraten] Er hatte mich gebeten dir zu sagen, dass er krank sei, er möchte lieber faulenzen."'
        - '!text "Dieser Faulpelz soll seinen Arsch hier her bewegen. Ich werde Roschik davon erzählen. Danke, dass du ehrlich zu mir warst."'