name: Des Händlers Bruder
desc: Finde Olafs Bruder
locked: false
author: Kiachan
ordered: true
hidden: true
required: 0
trigger:
  '0':
    type: host.interact
    args:
      host: world.bravaria.kia.des_haendlers_bruder.olaf
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.bravaria.kia.des_haendlers_bruder.olaf
          conv: world.bravaria.kia.des_haendlers_bruder.start-quest
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: world.bravaria.kia.des_haendlers_bruder.start-quest
      stage: accept
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.des_haendlers_bruder.start
      '1':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.des_haendlers_bruder.olaf
          conv: world.bravaria.kia.des_haendlers_bruder.olaf-1
      '2':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.emil
          conv: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.emil-find
objectives:
  '0':
    name: Finde Emil und rede mit ihm
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.emil-find
          stage: finished
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.emil
              conv: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.emil-end
          '1':
            type: rcconversations.host.save
            args:
              host: world.bravaria.kia.des_haendlers_bruder.olaf
              conv: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.complete-quest
  '1':
    name: Gehe zu Olaf zurück
    hidden: true
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.des_haendlers_bruder.1-der-bruder.complete-quest
          stage: stage1
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 150
  '1':
    type: player.give.money
    args:
      amount: 20s
  '2':
    type: rcconversations.host.save
    args:
      host: world.bravaria.kia.des_haendlers_bruder.olaf
      conv: world.bravaria.kia.des_haendlers_bruder.olaf-end
cooldown: 0
repeatable: false
