name: Säufer Angelegenheiten
desc: Bringe Jack eine Flasche Schnapps
locked: false
author: Kiachan
ordered: true
required: 0
trigger:
  '0':
    type: host.interact
    args:
      host: world.bravaria.kia.saufer_angelegenheiten.jack
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.bravaria.kia.saufer_angelegenheiten.jack
          conv: world.bravaria.kia.saufer_angelegenheiten.start-quest
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: world.bravaria.kia.saufer_angelegenheiten.start-quest
      stage: accept
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.saufer_angelegenheiten.start
      '1':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.saufer_angelegenheiten.jack
          conv: world.bravaria.kia.saufer_angelegenheiten.jack-1
      '2':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.lilli
          conv: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.lilli-kauf
      '3':
        type: player.give.money
        args:
          amount: 50k
  '2':
    type: host.interact
    args:
      host: world.bravaria.kia.saufer_angelegenheiten.jack
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.bravaria.kia.saufer_angelegenheiten.jack
          conv: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.complete-quest
    requirements:
      '0':
        type: quest.item.has
        args:
          item: Rotdornschnapps
          amount: 1
objectives:
  '0':
    name: Kaufe von Lilli eine Flasche Schnapps
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.lilli-kauf
          stage: deep1
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.lilli
              conv: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.lilli-end
          '1':
            type: rcconversations.host.save
            args:
              host: world.bravaria.kia.saufer_angelegenheiten.jack
              conv: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.complete-quest
          '2':
            type: quest.item.add
            args:
              item: Rotdornschnapps
              amount: 1
          '3':
            type: player.remove.money
            args:
              amount: 50k
  '1':
    name: Bringe Jack den Schnapps
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.saufer_angelegenheiten.saufer-angelegenheiten.complete-quest
          stage: finished
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 150
  '1':
    type: player.give.money
    args:
      amount: 70k
  '2':
    type: rcconversations.host.save
    args:
      host: world.bravaria.kia.saufer_angelegenheiten.jack
      conv: world.bravaria.kia.saufer_angelegenheiten.jack-end
  '3':
    type: quest.item.remove
    args:
      item: Rotdornschnapps
      amount: 1
cooldown: 0
repeatable: false
