settings:
  show-npc-name: true
stages:
  start:
    actions:
      flow:
        - '!player.freeze'
        - '!text "Hey, was machst du noch hier, der Bürgermeister hat zu einer Versammlung gerufen.", this.shicho'
        - '~5s'
        - '!text.player "Wieso, was ist los? Gab es wieder Ärger im Lager?"'
        - '~3s'
        - '!text "Schön wär’s, folge dem Weg links zur Versammlungshalle, du kannst es nicht verfehlen. Mach schnell die anderen warten schon.", this.shicho'
        - '~5s'
        - '!text.player "Und was mache ich dann?"'
        - '~2s'
        - '!text "Nimm Junnar mit, sie müsste auch schon längst los. Wenn ihr angekommen seid, sprecht sofort mit unserem Bürgermeister Roschik.", this.shicho'
        - '!text.info "Du kannst mit einem NPC per Rechtsklick sprechen"'
        - '~7s'
        - '!text.player "Ok, ich mache mich gleich auf den Weg."'
        - '~3s'
        - '!text "Bevor du gehst, vergiss nicht, dass du deine Aufgaben im Questlog notiert hast. Du kannst dein Questlog aus deinem Inventar öffnen. Und nun los geh zur Versammlungshalle.", this.shicho'
        - '~2s'
        - '!player.unfreeze'
        - '!quest.start this.ein-neuer-start'