name: Hungriges Faultier
region: frostak-hochebene
locked: false
abortable: true
authors:
  - LilianaVess (SuQ)
  - Silthus (QS)
worlds:
  - faldoria
level: 6

default-convs:
  completed:
    convs:
      - '../../npcs/anke:this.anke-quest-completed'
      - '../../npcs/tjorben:this.tjorben-quest-completed'

requirements:
  flow:
    - '?quest.active ../../hauptquest.2-vinnans-helfende.hand'

trigger:
  flow:
    - '@host.interact ../../npcs/tjorben this.quest-start'

objectives:
  '1':
    name: 'Besorge Tjorben ein Bier beim Wirt.'
    auto-complete: false
    hidden: true
    optional: true
    trigger:
      flow:
        - '@host.interact ../../npcs/stan this.stan-bier'
    tasks:
      '1':
        name: 'Besorge ein Bier beim Wirt.'
        hidden: true
        auto-complete: false
      '2':
        name: 'Erklärt Tjorben das er kein Bier mehr bekommt.'
        hidden: true
        auto-complete: false
        trigger:
          flow:
            - '@host.interact ../../npcs/tjorben this.tjorben-kein-bier'

  '2':
    name: 'Sammle 7 Knochenmark'
    desc: Besorgt von den Tieren im Umkreis von Jarmundshain 7 Knochenmark und bringt es zur Frau von Tjorben.
    auto-complete: true
    default-convs:
      completed:
        convs:
          - '../../npcs/anke:this.anke-quest-active'
          - '../../npcs/tjorben:this.tjorben-quest-active'
    trigger:
      flow:
        - '@item.pickup(count:7,count-text:"%current% von %count% Knochenmark gesammelt.") this.knochenmark'

  '3':
    name: 'Bringe das Knochenmark zur Frau von Tjorben'
    auto-complete: false
    default-convs:
      completed:
        convs:
          - '../../npcs/tjorben:this.tjorben-quest-active'
    trigger:
      flow:
        - '@host.interact ../../npcs/anke this.anke-quest-end'

  '4':
    name: 'Bringe Tjorben die Suppe.'
    auto-complete: false
    default-convs:
      completed:
        convs:
          - '../../npcs/anke:this.anke-suppe-active'
    trigger:
      flow:
        - '@host.interact ../../npcs/tjorben this.tjorben-quest-end'

complete-actions:
  flow:
    - '!item.remove "Leeres Papier" 1'
    - '!item.add this.zettel'
    - '!tag frostak-hochebene.vinnans-hilfe.nachweise'