stages:
  start:
    actions:
      flow:
        - '!text "Und der Tag ist perfekt.", ../mafei'
        - '~2s'
        - '!text.player "Was hast du gesagt Mafei?"'
        - '~2s'
        - '!text "Nichts, sag mir schnell was du willst und geh dann wieder.", ../mafei'
        - '~2s'
        - '!text.player "Der Bürgermeister schickt mich, du sollst das Schiff klar machen. Irgendwas von Weltuntergang oder so..."'
        - '~2s'
        - '!text "Wie bitte? Verarsch mich nicht.", ../mafei'
        - '~2s'
        - '!text.player "Nein, nein ehrlich, Agmagnum der Nekromant, hat Schiffe in unsere Richtung geschickt."'
        - '~2s'
        - '!text "Du meinst Agnatus? Wenn das einer deiner Späße wird, werde ich dich verprügeln.", ../mafei'
        - '~2s'
        - '!text.player "So glaub mir doch, du sollst das Schiff klar machen."'
        - '~2s'
        - '!text "Ok, dann kannst du mir behilflich sein. Du musst ein paar Vorräte für das Schiff zusammen suchen. Hier ist die Liste...", ../mafei'
        - '~1s'
        - '!player.give.item this.liste'
        - '~2s'
        - '!text.player "Ok werde ich machen."'
        - '~1s'
        - '!objective.complete this.vorraete 1'
        - '~5s'
        - '!text.info "Die Vorratsliste findest du in deinem Quest Inventar.\nKlicke dazu auf die Enderkiste in deinem Crafting Feld."'