stages:
  start:
    text: "Hast du die Vorräte?"
    answers:
      groups:
        complete:
          - '!player.remove.item this.items.getreide 10' # getreide
          - '!player.remove.item this.items.wassereimer' # wassereimer
          - '!player.remove.item this.items.holzbrett 10' # holzbretter
          - '!player.remove.item this.items.wolle 10' # wolle
          - '!player.remove.item this.vorrats-liste' # liste
          - '~1s'
          - '!text "Vielen Dank. Nun geh zurück zum Bürgermeister, er hat bestimmt noch mehr Aufgaben für dich.", ../mafei"'
          - '~2s'
          - '!objective.complete this.vorraete 3'
      flow:
        # Antwort 1
        - ':"Ja, hier hast du sie."'
        - '!complete'
        # Antwort 2
        - ':"Mir fehlen noch ein paar Vorräte."'
        - '!text "Dann solltest du dich beeilen.", ../mafei'