name: Freiheit
desc: Sprich mit Stanly
locked: false
author: Kiachan
ordered: false
required: 0
worlds:
- world
trigger:
  '0':
    type: quest.completed
    delay: 5
    args:
      quest: world.bravaria.kia.tutorial.5-handel.start-handel
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.tutorial.6-freiheit.start-freiheit
objectives:
  '0':
    name: Folge dem Kompass und sprich mit Stanly
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.tutorial.6-freiheit.stanly
          stage: stage2
        actions:
          '0':
            type: player.remove.compass
            args:
              name: Stanly
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 270
  '1':
    type: rcconversations.host.save
    args:
      host: world.bravaria.kia.tutorial.6-freiheit.stanly
      conv: world.bravaria.kia.tutorial.6-freiheit.stanly-end-quest
  '2':
    type: rcregions.unrestrict-to-region
    args:
      region: tutorial_kia
  '3':
    type: player.give.compass
    args:
      world: world
      x: 35
      y: 70
      z: 163
      name: Rüstmeister
cooldown: 0
repeatable: false
