stages:
  start: 
    text: Hallo Fremder. Du must neu in der Gegend sein, hast du einen|Moment Zeit?
    answers:
      '1':
        text: Ja klar.
        actions:
          A:
            type: STAGE
            args:
              stage: stage2
      '2':
        text: Nein keine Zeit!
        actions:
          A:
            type: TEXT
            args:
              text: Die jungen Leute von heute.. Keinen Gemeinschaftssinn pfffff
          B:
            type: END
  stage2:
    text: Mein Vater hat ein Problem.. Er bekommt das Feuer in der|Schmiede nicht zum brennen. Kannst du zu ihm gehen und|helfen?
    answers:
      '1':
        text: Ja natürlich!
        actions:
          A:
            type: STAGE
            args:
              stage: accept
      '2':
        text: Nein ich kann nicht!
        actions:
          A:
            type: TEXT
            args:
              text: Hast wohl Angst vorm Feuer?
          B:
            type: END
  accept:
    text: Wunderbar, er befindet sich in der Mine westlich von hier.
    actions:
      A:
        type: END