stages:
  start:
    text: '*Buddel Buddel*'
    answers:
      '1':
        text: Was machst du hier?
        actions:
          A:
            type: STAGE
            args:
              stage: stage2
        '2':
          text: .... der spinnt!
          actions:
            A:
              type: END
  stage2:
    text: Ich farme Erde, wir sind hier schließlich in einer &2Erdfarm!
    answers:
      '1':
        text: Oh, okay. Kannst du mir mehr darüber erzählen?
        actions:
          A:
            type: STAGE
            args:
              stage: stage3
      '2':
        text: Ja, dann farm mal weiter.
        actions:
          A:
            type: END
  stage3:
    text: Klar, kann ich. Es gibt Farmen für &2Kies&b, &2Sand&b, &2Stein&b, &2Erde&b,|&2Lehm&b und &2Holz&b.||Außerdem auch für &2Zucker&b und &2Weizen&b.||Gehe rüber zu den Zäunen und baue drei Blöcke ab.
  

