stages:
  start:
    actions:
      flow:
        - '!text "Ich hoffe, du weißt was du tust, aber du bist der Einzige, der gerade auf diese Reise gehen kann."'
        - '~4s'
        - '!text.player "Das ist etwas sehr Wichtiges, oder?"'
        - '~2s'
        - '!text "Ja, du wirst es großartig machen. Nun gut, aber du solltest dich noch etwas besser vorbereiten bevor ich dir die Erlaubnis geben kann, von hier fort zu gehen."'
        - '~8s'
        - '!text "Außerdem hilf doch den anderen hier im Camp auch noch bitte."'
        - '~4s'
        - '!text.player "Das mache ich. Welche Aufgabe hast du für mich denn noch?"'
        - '~4s'
        - '!stage quest'
  quest:
    text: 'Am Strand sind anscheinend einige Ruinen von Türmen, die einst wohl mal die Küste sichern sollten. Gehe doch dorthin und schaue ob du etwas Brauchbares findest.'
    answers:
      flow:
        - ':"Ich mache mich direkt auf den Weg."'
        - '!quest.start this.die-erlaubnis'