stages:
  start:
    text: "Hast du die Sachen?"
    answers:
      groups:
        end-quest:
          - '!text "Danke vielmals für die Hilfe!", this.kansa'
          - '!quest.completed this.lagerarbeiter'
          - '~1s'
          - '!text.player "Hab ich doch gern gemacht."'
        delay-quest:
          - '!text "Wir haben Zeit.", this.kansa'
          - '!end'
      flow:
        - '?objective.completed this.lagerarbeiter 1'
        - ':"Ja habe ich."'
        - '!end-quest'
        - ':"Nein, du musst dich noch gedulden."'
        - '!delay-quest'