name: Die Prüfung
desc: Beweise dich gegen die ersten Gegner
ordered: true
author: Raid-Craft Team
required: 0
worlds:
- world
locked: false
trigger:
  '0':
    type: host.interact
    args:
      host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
          conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-start
    requirements:
      '0':
        type: quest.active
        args:
          quest: world.bravaria.kia.tutorial.1-neuer-rekrut.start-neuer-rekrut
  '1':
    type: rcconversations.conversation.stage
    action-delay: 2
    args:
      conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-start
      stage: end
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.tutorial.2-die-prufung.start-die-prufung
      '1':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
          conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-change-class
      '2':
        type: rcregions.restrict-to-region
        args:
          region: start_area
objectives:
  '0':
    name: Besige 3 Monster im Trainingsraum
    trigger:
      '0':
        type: rcmobs.mob.kill
        args:
          mobs:
          - tutorial-training-schwerverbrecher
          - tutorial-training-verletzter_bandit
          - tutorial-training-banditen_schutze
    requirements:
      '0':
        type: dummy
        count: 3
        persistant: true
        count-text: '%current%/%count% Monster getötet.'
    actions:
      '0':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
          conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-training-beendet
  '1':
    name: Rede mit Wulfgar
    hidden: true
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-training-beendet
          stage: stage3
        actions:
          '1':
            type: rcconversations.host.save
            args:
              host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
              conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-change-class
  '2':
    name: Besiege 10 Monster im Prüfungsraum
    hidden: true
    trigger:
      '0':
        type: rcmobs.mob.kill
        args:
          mobs:
          - tutorial-prufung-schwerverbrecher
          - tutorial-prufung-verletzter_bandit
          - tutorial-prufung-banditen_schutze
    requirements:
      '0':
        type: dummy
        count: 10
        persistant: true
        count-text: '%current%/%count% Monster getötet.'
    actions:
      '0':
        type: rcconversations.host.save
        args:
          host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
          conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-prufung-beendet
  '3':
    name: Rede mit Wulfgar
    hidden: true
    trigger:
      '0':
        type: host.interact
        args:
          host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.bravaria.kia.tutorial.2-die-prufung.wulfgar
              conv: world.bravaria.kia.tutorial.2-die-prufung.wulfgar-prufung-beendet
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 1300
  '1':
    type: rcregions.unrestrict-to-region
    args:
      region: start_area
  '2':
    type: rcregions.restrict-to-region
    args:
      region: tutorial_kia
      message: Du bist noch nicht bereit Bravaria zu verlassen
  '3':
    type: player.give.compass
    args:
      world: world
      x: -1746
      y: 71
      z: -60
      name: Der Farmer
cooldown: 0
repeatable: false
