stages:
  start:
    text: '%player, bist du auch endlich wach, ja?'
    answers:
      flow:
        - '?tag ankanor.event.survivor'
        - '+:"Hauptmann Marduk hat uns dieser Aknetun erwischt oder warum sind wir plötzlich an einer Küste?"'
        - '!text "Du scheinst einen sehr festen Schlaf zu haben, letzte Nacht tobte ein übler Sturm, der das Schiff zerstörte und uns hier angespült hat. Wir haben dich einfach aus dem Schiffwrack geholt und dachten du wärst ohnmächtig."'
        - '~6s'
        - '!stage start-quest'
        - '-:"Hauptmann Marduk hat uns dieser Aknetun erwischt? Sind wir alle tot?"'
        - '!stage 2'
  '2':
    text: 'Nein, du wurdest ausgeknockt als du Agnatus Schergen bekämpft hast, man hat dich dann zum Schiff gebracht. Dort wurdest du versorgt.'
    answers:
      flow:
        - ':"Und wo sind wir hier? Das sieht mir nicht nach Ankanor aus."'
        - '!text "Wo genau wir sind weiß keiner, aber nein es ist nicht mehr Ankanor. Der Sturm letzte Nacht hat unser Schiff zerstört und wir wurden hier angespült."'
        - '~5s'
        - '!text.player "Ist das dein Ernst? Hmm... und was machen wir nun?"'
        - '~1s'
        - '!stage start-quest'
        - ':"Hmm... und was machen wir nun?"'
        - '!stage start-quest'
  start-quest:
    text: 'Ich habe zwar schon die Gegend ein wenig erkundet und sie scheint weitgehend unbewohnt zu sein. Aber ich habe ein Licht auf dem Hügel gesehen, ich kann hier nicht weg, ich muss das Camp beschützen. Schau dir das mal an und berichte mir dann.'
    answers:
      flow:
        - ':"Jawohl!"'
        - '!objective.complete this.was-ist-passiert 1'
        - '!end'