name: Verrückte Hexe
desc: Bring das verhexte Ei zur Hexe
locked: true
author: Kiachan
ordered: true
hidden: true
required: 0
trigger:
  '0':
    type: rcitems.item.pickup
    args:
      type: QUEST
      id: 90934
    actions:
      '0':
        type: player.give.compass
        args:
          world: world
          x: 497
          y: 63
          z: 2880
          name: Die Hexe
      '1':
        type: quest.start
        args:
          quest: world.ostern.verrueckte_hexe.start-verrueckte_hexe
objectives:
  '0':
    name: Bringe das Ei zur Hexe
    trigger:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.ostern.verrueckte_hexe.start-quest
          stage: accept
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.ostern.verrueckte_hexe.hexe
              conv: world.ostern.verrueckte_hexe.1-hexe
          '1':
            type: quest.item.remove
            args:
              item: 90934
              amount: 1
          '2':
            type: rcconversations.conversation.start
            args:
              host: world.ostern.verrueckte_hexe.hexe
              conv: world.ostern.verrueckte_hexe.start-quest
    requirements:
      '0':
        type: quest.item.has
        args:
          item: 90934
          amount: 1
  '1':
    name: Kämpfe dich aus der Höhle und gehe zur Hexe zurück.
    hidden: true
    trigger:
      '0':
        type: player.move
        args:
          world: world
          x: 381
          y: 63
          z: 2822
          radius: 3
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.ostern.verrueckte_hexe.hexe
              conv: world.ostern.verrueckte_hexe.complete-quest
    requirements:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.ostern.verrueckte_hexe.complete-quest
          stage: finished
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 400
  '1':
    type: rcconversations.host.save
    args:
      host: world.ostern.verrueckte_hexe.hexe
      conv: world.ostern.verrueckte_hexe.end-quest
  '3':
    type: quest.item.add
    args:
      item: 90970
      amount: 40
  '4':
    type: player.give.money
    args:
      amount: 3g50k
cooldown: 0
repeatable: false
