name: Ostereierdiebe
desc: Bring Lisa die Ostereier von den Dieben zurück
locked: true
author: Kiachan
ordered: true
hidden: true
required: 0
trigger:
  '0':
    type: host.interact
    args:
      host: world.ostern.osterei_diebe.lisa
    actions:
      '0':
        type: rcconversations.conversation.start
        args:
          host: world.ostern.osterei_diebe.lisa
          conv: world.ostern.osterei_diebe.start-quest
  '1':
    type: rcconversations.conversation.stage
    args:
      conv: world.ostern.osterei_diebe.start-quest
      stage: accept
    actions:
      '0':
        type: quest.start
        args:
          quest: world.ostern.osterei_diebe.start-osterei_diebe
      '1':
        type: rcconversations.host.save
        args:
          host: world.ostern.osterei_diebe.lisa
          conv: world.ostern.osterei_diebe.1-lisa
objectives:
  '0':
    name: Erbeute 6 grüne Ostereier.
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          type: QUEST
          id: 90926
    requirements:
      '0':
        type: dummy
        count: 6
        persistant: true
        count-text: '%current%/%count% grüne Ostereier gesammelt.'
  '1':
    name: Erbeute 6 rote Ostereier
    hidden: true
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          type: QUEST
          id: 90929
    requirements:
      '0':
        type: dummy
        count: 6
        persistant: true
        count-text: '%current%/%count% rote Ostereier gesammelt.'
  '2':
    name: Erbeute 6 blaue Ostereier
    hidden: true
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          type: QUEST
          id: 90932
    requirements:
      '0':
        type: dummy
        count: 6
        persistant: true
        count-text: '%current%/%count% blaue Ostereier gesammelt.'
  '3':
    name: Erbeute 6 pinke Ostereier
    hidden: true
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          type: QUEST
          id: 90931
    requirements:
      '0':
        type: dummy
        count: 6
        persistant: true
        count-text: '%current%/%count% pinke Ostereier gesammelt.'
  '4':
    name: Erbeute 6 gelb Ostereier.
    hidden: true
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          type: QUEST
          id: 90927
    requirements:
      '0':
        type: dummy
        count: 6
        persistant: true
        count-text: '%current%/%count% gelbe Ostereier gesammelt.'
  '5':
    name: Erbeute 6 türkise Ostereier
    hidden: true
    trigger:
      '0':
        type: rcitems.item.pickup
        args:
          type: QUEST
          id: 90938
    requirements:
      '0':
        type: dummy
        count: 6
        persistant: true
        count-text: '%current%/%count% türkise Ostereier gesammelt.'
  '6':
    name: Kehre zu Lisa zurück
    hidden: true
    trigger:
      '0':
        type: host.interact
        args:
          host: world.ostern.osterei_diebe.lisa
        actions:
          '0':
            type: rcconversations.host.save
            args:
              host: world.ostern.osterei_diebe.lisa
              conv: world.ostern.osterei_diebe.complete-quest
    requirements:
      '0':
        type: quest.item.has
        args:
          item: 90926
          amount: 6
      '1':
        type: quest.item.has
        args:
          item: 90929
          amount: 6
      '3':
        type: quest.item.has
        args:
          item: 90932
          amount: 6
      '4':
        type: quest.item.has
        args:
          item: 909031
          amount: 6
      '5':
        type: quest.item.has
        args:
          item: 90927
          amount: 6
      '6':
        type: quest.item.has
        args:
          item: 90938
          amount: 6
  '7':
    name: Rede mit Lisa
    hidden: true
    trigger:
      '0':
        type: host.interact
        args:
          host: world.ostern.osterei_diebe.lisa
    requirements:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: world.ostern.ostereie_diebe.complete-quest
          stage: finished
complete-actions:
  '0':
    type: quest.item.remove
    args:
      item: Grünes Osterei
      amount: 6
  '1':
    type: quest.item.remove
    args:
      item: Gelbes Osterei
      amount: 6
  '2':
    type: quest.item.remove
    args:
      item: Rotes Osterei
      amount: 6
  '3':
    type: quest.item.remove
    args:
      item: Pinkes Osterei
      amount: 6
  '4':
    type: quest.item.remove
    args:
      item: Blaues Osterei
      amount: 6
  '5':
    type: quest.item.remove
    args:
      item: Türkises Osterei
      amount: 6
  '6':
    type: rcskills.hero.addxp
    args:
      exp: 250
  '7':
    type: rcconversations.host.save
    args:
      host: world.ostern.osterei_diebe.lisa
      conv: world.ostern.osterei_diebe.end-quest
  '8':
    type: quest.item.add
    args:
      item: 90970
      amount: 30
cooldown: 0
repeatable: false
