name: Die Flucht
desc: Entkomme aus dem Gefängnis
locked: false
author: Kiachan
ordered: true
hidden: true
required: 0
trigger:
  '0':
    type: quest.completed
    args:
      quest: world.wyzima.petz
  '1':
    type: player.move
    args:
      world: world
      x: 64
      y: 58
      z: 205
    actions:
      '0':
        type: quest.start
        args:
          quest: this.start-flucht
      '1':
        type: rcconversations.conversation.start
        args:
          host: this.timo
          conv: this.complete-quest
objectives:
  '0':
    name: Rede mit Timo
    trigger:
      '0':
        type: host.interact
        args:
          host: this.timo
    requirements:
      '0':
        type: rcconversations.conversation.stage
        args:
          conv: this.complete-quest
          stage: finished
        actions:
          '0':
            type: block.set
            args:
              x: 65
              y: 59
              z: 205
              world: world
              block: 0
          '1':
            type: block.set
            args:
              x: 65
              y: 58
              z: 205
              world: world
              block: 0
          '2':
            type: block.set
            args:
              x: 65
              y: 59
              z: 206
              world: world
              block: 0
          '3':
            type: block.set
            args:
              x: 65
              y: 58
              z: 206
              world: world
              block: 0
  '1':
    name: Entkomme aus dem Gefängniss
    hidden: true
    trigger:
      '0':
        type: player.move
        args:
          world: world
          x: 65
          y: 21
          z: 198
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 500
  '1':
    type: rcconversations.host.save
    args:
      host: this.timo
      conv: this.end-quest
  '2':
    type: block.set
    args:
      x: 65
      y: 59
      z: 205
      world: world
      block: 98
  '3':
    type: block.set
    args:
      x: 65
      y: 58
      z: 205
      world: world
      block: 98
  '4':
    type: block.set
    args:
      x: 65
      y: 59
      z: 206
      world: world
      block: 98
  '5':
    type: block.set
    args:
      x: 65
      y: 58
      z: 206
      world: world
      block: 98