name: R端ste dich
desc: Sprich mit dem R端stmeister am Spawn
locked: false
author: Kiachan
ordered: false
required: 0
worlds:
- world
trigger:
  '0':
    type: quest.completed
    delay: 5
    args:
      quest: world.bravaria.kia.tutorial.6-freiheit.start-freiheit
    actions:
      '0':
        type: quest.start
        args:
          quest: world.bravaria.kia.tutorial.7-rueste-dich.start-rueste-dich
objectives:
  '0':
    name: Sprich mit dem R端stmeister am RC-Spawn
    trigger:
      '0':
        type: host.interact
        args:
          host: world.bravaria.kia.tutorial.7-rueste-dich.ruestmeister
        actions:
          '0':
            type: rcconversations.conversation.start
            args:
              conv: world.bravaria.kia.tutorial.7-rueste-dich.ruestmeister
          '1':
            type: player.give.item
            args:
              item: 355
              amount: 1
          '2':
            type: player.give.item
            args:
              item: 54
              amount: 1
          '3':
            type: player.give.item
            args:
              item: 50
              amount: 64
          '4':
            type: player.give.item
            args:
              item: 65
              amount: 64
          '5':
            type: player.give.item
            args:
              item: 58
              amount: 1
          '6':
            type: player.give.item
            args:
              item: 393
              amount: 64
          '7':
            type: player.give.item
            args:
              item: rc1
              amount: 1
          '8':
            type: quest.item.remove
            args:
              item: Rc90907
              amount: 1
          '9':
            type: player.remove.compass
            args:
              name: R端stmeister
        requirements:
          '0':
            type: player.has-item
            args:
              item: rc90907
              amount: 1
complete-actions:
  '0':
    type: rcskills.hero.addxp
    args:
      exp: 270
  '1':
    type: rcconversations.host.save
    args:
      host: world.bravaria.kia.tutorial.7-rueste-dich.ruestmeister
      conv: world.bravaria.kia.tutorial.7-rueste-dich.ruestmeister-end-quest
  '2':
    type: player.give.compass
    args:
      world: world
      x: 330
      y: 64
      z: -172
      name: Die neuen Slums
cooldown: 0
repeatable: false
